print('CALCULADORA MEGA CALCULOS')
numero1 = int(input('Primeiro número: '))
print(f' Você digitou o número: {numero1}')
numero2 = int(input('Segundo número: '))
print(f' Você digitou o número: {numero2}')
print(f' Resultado da soma: {numero1+numero2}')
print(f' Resultado da subtração: {numero1-numero2}')
print(f' Resultado da multiplicação: {numero1*numero2}')
print(f' Resultado da divisão inteira: {numero1//numero2}')