cateto1 = int(input('Me informe o cateto1= '))
print(f'O cateto1 é o: {cateto1}')
cateto2 = int(input('Me informe o cateto2= '))
print(f'O cateto2 é o: {cateto2}')
print(f'Valor da hipotenusa: ({(cateto1**2+cateto2**2)**(1/2)})')